//=========================================================================
//=================== 2014 03 12  GEM DEFINE =========================//
/*********************************************************/

#define		RESULT_OK		0x00
#define		WM_TERMMSG_ACK		WM_USER+10000
#define		MAX_LOG_COUNT		100
#define		TIMERID_START			1001		//ADD 2014 07 25
#define		TIMER_SVID_CLOCK		1002		//ADD 2014 07 25
#define		TIMERID_SETVIEW			1003		//ADD 2014 07 25
#define		TIMERID_TEST			1004		//ADD 2014 07 25


#define		MAX_TERMINAL_COUNT				30


#define		ASCII_CODE_0					48
#define		ASCII_CODE_9					57

//================================================================
// PARAMETER NAME

//#define		PARAM_TOP_WAFER_PRESSURE			"TOP_WAFER_PRESSURE"		
//#define		PARAM_CHUCK_HIGH_PRESSURE			"CHUCK_HIGH_PRESSURE"
//#define		PARAM_CHUCK_LOW_PRESSURE			"CHUCK_LOW_PRESSURE"	
//#define		PARAM_CHUCK_N2_DRY_RPM				"CHUCK_N2_DRY_RPM"			
//#define		PARAM_HIGH_PRESSURE_TIME			"HIGH_PRESSURE_TIME"	
//#define		PARAM_LOW_PRESSURE_TIME				"LOW_PRESSURE_TIME"	
//#define		PARAM_N2_DRY_TIME					"N2_DRY_TIME"


//=================================================================

//=================== CONTROL =========================
///////////// Control State /////////////////

typedef enum
{
	PROCESS_STATE_PRODUCTIVE				=	1, //== RUN
		PROCESS_STATE_STANDBY					=	2, //== IDLE
		PROCESS_STATE_ENGINEERING				=	3, //== DRY RUN
		
		PROCESS_STATE_SCHEDULED_DOWNTIME		=	4, //== PM
		
		PROCESS_STATE_UNSCHEDULED_DOWNTIME		=	5, //== Alarm Down
		PROCESS_STATE_NON_SCHEDULED_TIME		=	6, //== UNKNOWN
		
} PROCESS_STATE;

typedef enum
{
		PROCESS_MODE_OFFLINE_STAND_ALONE			=	0,
	//	PROCESS_MODE_OFFLINE_INTEGRATED				=	1,
	//	PROCESS_MODE_OFFLINE_DOWNSTREAM_INTEGRATED			=	2,
	//	PROCESS_MODE_OFFLINE_UPSTREAM_INTEGRATED			=	3,
		PROCESS_MODE_ONLINE_STAND_ALONE				=	1,
		PROCESS_MODE_ONLINE_SPLIT_MODE				=	2,
	//	PROCESS_MODE_ONLINE_DOWNSTREAM_INTEGRATED_WAFER		=	6,
	//	PROCESS_MODE_ONLINE_UPSTREAM_INTEGRATED_WAFER		=	7,
		
} PROCESS_MODE;

typedef enum
{
		OPERATION_MODE_STAND_ALONE						=	0,
	//	OPERATION_MODE_FULL_INTEGRATED					=	1,
	//	OPERATION_MODE_DOWNSTREAM_INTEGRATED			=	2,
	//	OPERATION_MODE_UPSTREAM_INTEGRATED				=	3,
		
} OPERATION_MODE;


///////////// Control State /////////////////
typedef enum
{
	CONTROL_UNKOWN = 0,
		CONTROL_OFFLINE = 0,
		CONTROL_GOING_TO_ONLINE = 0,
		CONTROL_HOST_OFFLINE = 0,
		CONTROL_ONLINE_LOCAL = 1,
		CONTROL_ONLINE_REMOTE = 2,
		CONTROL_STOP = 3,
} CONTROL_STATE;

///////////// Control State /////////////////
typedef enum
{
	CONTROL_DISCONNECTED = 0,
	CONTROL_CONNECTED = 1,
} CONTROL_CONNECT;

typedef enum
{
	DFFAULT_EQUIPMENT_OFFLINE = 0,
		DEFAULT_HOST_OFFLINE = 0,
		DEFAULT_ONLINE_LOCAL = 1,
		DEFAULT_ONLINE_REMOTE = 2
} DEFAULT_CONTROL_STATE;


//=========== HSMS SETTING ================================
#define			HSMS			"HSMS"
#define			HSMS_PORT		"PORT"
#define			HSMS_DEVICEID	"DEVICEID"
#define			HSMS_LINKTEST	"LINKTEST"
#define			HSMS_RETRY		"RETRY"
#define			HSMS_T3			"T3"
#define			HSMS_T5			"T5"
#define			HSMS_T6			"T6"
#define			HSMS_T7			"T7"
#define			HSMS_T8			"T8"

#define			RECIPE										"RECIPE"
#define		TAPE_TAG					"TAPE_TAG"
#define		TAPE_CHANGED_TIME			"TAPE_CHANGED_TIME"


//============ Log Define	==============================
#define			DEFAULT_MAX_LOG_SIZE			1000
#define			DEFAULT_MAX_LOG_ENABLE			FALSE

//=========== HSMS SETTING ================================
#define			GEM_GEM			"GEM"
#define			GEM_DEFAULT_CONTROLSTATE		"DefaultControlState"
#define			GEM_MAXLOG_SIZE		"MaxLogSize"
#define			GEM_LOG_RETENSIION		"LogRetension"
#define			GEM_WLOG_RETENSION		"WLogRetension"
#define			GEM_OLOG_RETENSION		"OLogRetension"
#define			GEM_ALOG_RETENSION		"ALogRetension"
#define			GEM_LOG_ENABLE			"LogEnable"
#define			GEM_WLOG_ENABLE		"WLogEnable"
#define			GEM_OLOG_ENABLE		"OLogEnable"
#define			GEM_ALOG_ENABLE		"ALogEnable"


//============ Remote Comment ============================

#define		RCMD_START						     "START"
#define		RCMD_STOP                            "STOP"
#define		RCMD_LOGIN                           "LOGIN"
#define		RCMD_LOOUT                           "LOOUT"

#define		RCMD_CHANGE_MODE			     "CHANGE_MODE"

#define		RCMD_LOAD_CARRIER			     "LOAD_CARRIER"
#define		RCMD_UNLOAD_CARRIER				 "UNLOAD_CARRIER"
#define		RCMD_REJECT_CARRIER			     "REJECT_CARRIER"

#define		RCMD_PROCESS_CARRIER			     "PROCESS_CARRIER"

#define		RCMD_LOAD_REJECT_CARRIER			     "LOAD_REJECT_CARRIER"
#define		RCMD_UNLOAD_REJECT_CARRIER				 "UNLOAD_REJECT_CARRIER"

#define		RCMD_SELECT_WAFER_SCRIBES			     "SELECT_WAFER_SCRIBES"
#define		RCMD_SELECT_SLOT_NUMBERS			     "SELECT_SLOT_NUMBERS"

#define		RCMD_START_WAFER						    "START_WAFER"
#define		RCMD_ABORT_WAFER                            "ABORT_WAFER"

#define		RCMD_LOAD_WAFER_RECIPE			"LOAD_WAFER_RECIPE"


#define		RCMD_SET_WAFER_APC_PARAMETERS      "SET_WAFER_APC_PARAMETERS"


#define		RCMD_ABORT_CARRIER					 "ABORT_CARRIER"


#define		RCMD_START_INPUT						   "START_INPUT"
#define		RCMD_STOP_INPUT                            "STOP_INPUT"
#define		RCMD_STOP_INPUT_AFTER_N_WAFERS            "STOP_INPUT_AFTER_N_WAFERS"
#define		RCMD_STOP_OUTPUT                           "STOP_OUTPUT"
#define		RCMD_STOP_OUTPUT_AFTER_N_WAFERS            "STOP_OUTPUT_AFTER_N_WAFERS"
#define		RCMD_START_OUTPUT						   "START_OUTPUT"
#define		RCMD_SPLIT								   "SPLIT"

#define     RCMD_START_TRANSFER							"START_TRANSFER"
#define     RCMD_SELECT_IN_WAFERS						"SELECT_INPUT_WAFERS"
#define     RCMD_SELECT_IN_SLOT							"SELECT_INPUT_SLOT_NUMBERS"
#define     RCMD_SELECT_IN_AUTO							"SELECT_AUTO_INPUT_SLOT_NUMBERS"
#define     RCMD_SELECT_OUT_SLOT						"SELECT_OUTPUT_SLOT_NUMBERS"
#define     RCMD_SELECT_OUT_AUTO						"SELECT_AUTO_OUTPUT_SLOT_NUMBERS"

//===============================================================================
// CPNAME

#define		CPNAME_APC_PARAMETER_LIST				"APC_PARAMETER_LIST"
#define		CPNAME_APC_PARAMETER_NAME				"APC_PARAMETER_NAMES"
#define		CPNAME_APC_PARAMETER_VALUE				"APC_PARAMETER_VALUES"

//==============================================================
#define		CPNAME_REASON						"REASON"
#define		CPNAME_ERROR_CODE					"ERROR_CODE"
#define		CPNAME_ERROR_DESCRIPTION			"ERROR_DESCRIPTION"


#define		CPNAME_RECIPE_ID					"RECIPE_ID"
#define		CPNAME_CARRIER_ID					"CARRIER_ID"
#define		CPNAME_PROCESS_MODE					"PROCESS_MODE"

#define		CPNAME_WAFER_ID						"WAFER_ID"
#define		CPNAME_SLOT_NUMBERS					"SLOT_NUMBERS"
#define		CPNAME_PORT_NUMBERS					"PORT_NUMBERS"

#define		CPNAME_INPUT_CARRIERID					"INPUT_CARRIER_ID"
#define		CPNAME_WAFER_IDS					"WAFER_IDS"

#define		CPNAME_USER_ID						"USER_ID"

#define		CPNAME_LOAD_PORT						"LOADPORT"

#define		CPNAME_STATION_ID					"STATION_ID"
#define		CPNAME_N_WAFERS						"N_WAFERS"


//========= ACP =============


#define		APC_PARAM_TAPE_EXPAND_LENGTH			"TAPE_EXPAND_LENGTH"
#define		APC_PARAM_TAPE_EXPAND_SPEED				"TAPE_EXPAND_SPEED"	

#define		APC_PARAM_TAPE_EXPAND_HEAT_TIME			"TAPE_EXPAND_HEAT_TIME"	
#define		APC_PARAM_TAPE_EXPAND_END_WAIT_TIME		"TAPE_EXPAND_END_WAIT_TIME"
#define		APC_PARAM_OUTER_RING_LOCK_SPEED			"OUTER_RING_LOCK_SPEED"



//////////////////////////////////////////////////////////
#define			ECID_MOUNT_CHUCK_TEMP								9000
#define			ECID_DETAPE_CHUCK_TEMP								9001
#define			ECID_DETAPE_HEATERBAR_TEMP							9002

//#define			ECID_CONTROL_STATE					3000
#define			ECID_ESTABLISH_TIMEOUT				4001
#define			ECID_T3								4002
#define			ECID_T5								4003
#define			ECID_T6								4004
#define			ECID_T7								4005
#define			ECID_T8								4006
#define			ECID_CONVERSATION_TIMEOUT			4007
#define			ECID_LINKTEST						4008
#define			ECID_RETRY							4009

#define			ECID_DEFAULT_COMM_STATE				4010
#define			ECID_DEFAULT_CONTROL_STATE			4011

#define			ECID_MAX_SPOOL_SIZE					4012
#define			ECID_MAXSPOOL_TRANSMIT				4013
#define			ECID_SPOOL_OVERWRITE				4014
#define			ECID_SPOOLING_MODE					4015

#define			ECID_TIME_FORMAT					4016
#define			ECID_JOBINFO_OPCONFIRM				4017
#define			ECID_IDLE_TIME						4018



//===========================================================================
//============= CARRIER TYPE ================================================

#define			NO_CASSETTE						"0"
#define			WITH_CASSETTE					"1"

#define			FOUP_UNLOAD						"0"
#define			FOUP_LOAD						"1"

#define			MODULE_ALL						0
#define			MODULE_LAMICHUCK				1
#define			MODULE_DECOVERCHUCK				2

//=================== GEM EVENT =============================================
//=================== GEM EVENT =============================================


#define		CEID_CONTROL_STATE_CHANGED														1000							
#define		CEID_PROCESS_STATE_CHANGED														1001
#define		CEID_ALL_LOAD_PORTS_EMPTY														1002							
#define		CEID_ALL_LOAD_PORTS_FULL														1003
#define		CEID_MACHINE_INITIALIZED														1004							
#define		CEID_MACHINE_STARTED															1005							
#define		CEID_MACHINE_STOPED																1006
#define		CEID_RUN_MODE_CHANGED															1007
#define		CEID_PROCESS_MODE_CHANGED														1008
#define		CEID_PROCESS_CONTROL_PARAMETER_CHANGED											1009
#define		CEID_MACHINE_RECOVERY_FORM_PREVIOUS												1010						
#define		CEID_MACHINE_COMPONENT_FAILURE													1011
#define		CEID_MACHINE_INITIALIZATION_FAILURE												1012
#define		CEID_PROCESS_INTEGRITY_ERROR													1013
#define		CEID_REQUEST_PROCESS_INTEGRITY_CHECK											1014
#define		CEID_GENERIC_MACHINE_ERROR														1015							
#define		CEID_MACHINE_PURGED																1016
#define		CEID_PRINTER_OUT_OF_STICKER_LABEL												1017							
#define		CEID_STICKER_LABELS_RELOADED_TO_PRINTER											1018
#define		CEID_USER_LOGIN																	1019							
#define		CEID_USER_LOTOUT																1020
#define		CEID_EXPAND_CHUCK_TABLE_MACHINICAL_CHANGE_OVER_COMPLETE							1021							
#define		CEID_EXPAND_CHUCK_RING_FRAME_GUID_MACHINICAL_CHANGE_OVER_COMPLETE				1022							
#define		CEID_INNER_GRIP_RING_TRANSFER_MACHINICAL_CHANGE_OVER_COMPLETE					1023							
#define		CEID_OUTER_GRIP_RING_TRANSFER_MACHINICAL_CHANGE_OVER_COMPLETE					1024							
#define		CEID_INNER_GRIP_RING_STACK_MACHINICAL_CHANGE_OVER_COMPLETE						1025							
#define		CEID_OUTER_GRIP_RING_STACK_MACHINICAL_CHANGE_OVER_COMPLETE						1026
#define		CEID_INPUT_STARTED																1027							
#define		CEID_INPUT_STOPPED																1028
#define		CEID_OUTPUT_STARTED																1029							
#define		CEID_OUTPUT_STOPPED																1030


#define		CEID_LOAD_PORT_ENABLED															1200
#define		CEID_LOAD_PORT_DISABLED															1201
#define		CEID_LOAD_PORT_OCCUPIED															1202
#define		CEID_LOAD_PORT_EMPTY															1203
#define		CEID_REQUEST_WAFER_CARRIER_LOAD													1204							
#define		CEID_WAFER_CARRIER_LOADED														1205//							
#define		CEID_WAFER_CARRIER_LOAD_FAILURE													1206
#define		CEID_REQUEST_WAFER_CARRIER_ABORT												1207							
#define		CEID_WAFER_CARRIER_ABORTED														1208							
#define		CEID_WAFER_CARRIER_ABORT_FAILURE												1209
#define		CEID_REQUEST_WAFER_CARRIER_UNLOAD												1210							
#define		CEID_WAFER_CARRIER_UNLOADED														1211//							
#define		CEID_WAFER_CARRIER_UNLOAD_FAILURE												1212
#define		CEID_UNEXPECTED_WAFER_CARRIER_DETECTED											1213//
#define		CEID_UNEXPECTED_WAFER_CARRIER_REMOVAL											1214
#define		CEID_WAFER_CARRIER_ID_UNREADABLE												1215							
#define		CEID_WAFER_CARRIER_ID_MANUALLY_INPUTTED											1216							
#define		CEID_READY_TO_LOAD_THE_NEXT_WAFER_CARRIER										1217							
#define		CEID_READY_TO_UNLOAD_THE_FINISHED_WAFER_CARRIER									1218
#define		CEID_WAFER_CARRIER_TYPE_DID_NOT_MATCH_EQUIPMENT_CONFIGURATION					1219
#define		CEID_REQUES_WAFER_CARRIER_PROCESSED												1220
#define		CEID_WAFER_CARRIER_REJECTED														1221
#define		CEID_WAFER_CARRIER_STARTED_PROCESSING											1222
#define		CEID_WAFER_CARRIER_FINISHED_PROCESSING											1223
#define		CEID_RECIPE_LOAD_FOR_WAFER_SUCCESSFULLY_ASSIGNED								1224
#define		CEID_RECIPE_LOAD_FOR_WAFER_FAILED												1225
#define		CEID_APC_PARAMETERS_LOAD_FOR_WAFER_SUCCESSFULLY_ASSIGNED						1226
#define		CEID_APC_PARAMETERS_LOAD_FOR_WAFER_FAILED										1227
// 
#define		CEID_INPUT_WAFER_SELECT															1230 // new
#define		CEID_INPUT_SLOTNUMBER_SELECT													1231 //	new
#define		CEID_OUTPUT_SLOTNUMBER_SELECT													1232 // new
#define		CEID_OUTPUT_AUTO_SLOTNUMBER_SELECT												1233 // new

// 							

#define		CEID_WAFER_LOADED_TO_WAFER_ID_READ_MODULE											1800
#define		CEID_WAFER_UNLOADED_FROM_WAFER_ID_READ_MODULE										1801
#define		CEID_WAFER_ERROR_AT_WAFER_ID_READ_MODULE											1802
#define		CEID_WAFER_ID_UNREADABLE_AT_WAFER_ID_READ_MODULE									1803
#define		CEID_WAFER_ID_MANUALLY_TYPED_AT_WAFER_ID_READ_MODULE								1804
#define		CEID_REQUEST_TO_PROCESS_WAFER														1805
#define		CEID_WAFER_LOADED_TO_STRETCHING_MODULE												1806
#define		CEID_WAFER_TAPE_STRETCHED															1807
#define		CEID_OUTER_RING_PICKED_FROM_STACKER													1808
#define		CEID_OUTER_RING_PUT_AROUND_STRETCHED_WAFER_TAPE										1809
#define		CEID_WAFER_RING_UNLOADED_FROM_STRETCHING_MODULE										1810
#define		CEID_BARCODE_LABEL_PRINTED															1811
#define		CEID_BARCODE_LABEL_ATTACHED_TO_WAFER_TAPE											1812
#define		CEID_BARCODE_LABEL_MATCHED_WAFER_ID													1813
#define		CEID_BARCODE_LABEL_DID_NOT_MATCH_WAFER_ID											1814
#define		CEID_OUTER_RING_STACKER_EMPTY														1815
#define		CEID_OUTER_RING_STACKER_RELOADED													1816
#define		CEID_WAFER_UNLOADED_FROM_RING_FRAME_CASSETTE										1817
#define		CEID_WAFER_UNLOAD_ERROR_FROM_RING_FRAME_CASSETTE									1818
#define		CEID_WAFER_LOADED_TO_RING_FRAME_CASSETTE											1819
#define		CEID_WAFER_LOAD_ERROR_AT_RING_FRAME_CASSETTE										1820
#define		CEID_WAFER_STARTED_PROCESSING														1821
#define		CEID_WAFER_FINISHED_PROCESSING														1822
#define		CEID_WAFER_ABORTED																	1823
#define		CEID_WAFER_MANUAL_REMOVED															1824
#define		CEID_INNER_GRIP_RING_EMPTY															1825
#define		CEID_INNER_RING_STACKER_RELOADED													1826
#define		CEID_REQUEST_START_WAFER_TRANSFER													1827
#define     CEID_WAFER_SPLIT_COMPLETED															1828
#define     CEID_WAFER_OUTPUT_CASSETTE_SLOT_CHECK_ERROR											1829

//===========================================================================================================

#define		CEID_RECIPE_CREATED																	1500
#define		CEID_RECIPE_MODIFYED																1501
#define		CEID_RECIPE_DELETED																	1502
#define		CEID_RECIPE_CHANGED																	1503


//======================= GEM SVID ===============================

#define		SVID_CONTROL_STATE																		3000							
#define		SVID_CURRENT_CONTROL_STATE																3001							
#define		SVID_PREVIOUS_CONTROL_STATE																3002							
#define		SVID_CURRENT_PROCESS_STATE																3003							
#define		SVID_PREVIOUS_PROCESS_STATE																3004							
#define		SVID_MOST_RECENT_MACHINE_ERROR															3005	
#define		SVID_CURRENT_RUN_MODE																	3006	
#define		SVID_PREVIOUS_RUN_MODE																	3007	
#define		SVID_CURRENT_USER_ID																	3008							
#define		SVID_MACHINE_ID																			3009							
#define		SVID_MACHINE_MODEL																		3010							
#define		SVID_MACHINE_SOFTWARE_REVISION_NUMBER													3011							
#define		SVID_MACHINE_SOFTWARE_REVISION_DATE														3012							
#define		SVID_DESCRIPTION_OF_MACHINE_COMPONENT_FAILURE											3013							
#define		SVID_DESCRIPTION_OF_GENERIC_MACHINE_ERROR												3014
#define		SVID_WAFER_COUNT_SINCE_LAST_PREVENTIVE_MAINTENANCE										3015
#define		SVID_REQUESTED_NEW_RUN__MODE															3016
#define		SVID_OPERATION_MODE																		3017
#define		SVID_ENABLE_DISABLE_STATUS_OF_LOAD_PORT_1												3020
#define		SVID_ENABLE_DISABLE_STATUS_OF_LOAD_PORT_2												3021
#define		SVID_ENABLE_DISABLE_STATUS_OF_LOAD_PORT_3												3022
#define		SVID_ENABLE_DISABLE_STATUS_OF_LOAD_PORT_4												3023
#define		SVID_OCCUPIED_EMPTY_STATUS_OF_LOAD_PORT_1												3030
#define		SVID_OCCUPIED_EMPTY_STATUS_OF_LOAD_PORT_2												3031
#define		SVID_OCCUPIED_EMPTY_STATUS_OF_LOAD_PORT_3												3032
#define		SVID_OCCUPIED_EMPTY_STATUS_OF_LOAD_PORT_4												3033
#define		SVID_CURRENT_PROCESS_MODE_STATE															3034
#define		SVID_EXPAND_CHUCK_TABLE_MACHINICAL_CHANGE_OVER_COMPLETE									3035							
#define		SVID_EXPAND_CHUCK_RING_FRAME_GUID_MACHINICAL_CHANGE_OVER_COMPLETE						3036							
#define		SVID_INNER_GRIP_RING_TRANSFER_MACHINICAL_CHANGE_OVER_COMPLETE							3037							
#define		SVID_OUTER_GRIP_RING_TRANSFER_MACHINICAL_CHANGE_OVER_COMPLETE							3038							
#define		SVID_INNER_GRIP_RING_STACK_MACHINICAL_CHANGE_OVER_COMPLETE								3039							
#define		SVID_OUTER_GRIP_RING_STACK_MACHINICAL_CHANGE_OVER_COMPLETE								3040


#define		SVID_CLOCK																				3100


#define		SVID_LOAD_PORT_ENABLE_NUMBER															3200
#define		SVID_LOAD_PORT_DISABLE_NUMBER															3201
#define		SVID_LOAD_PORT_OCCUPIED_NUMBER															3202
#define		SVID_LOAD_PORT_EMPTY_NUMBER																3203
#define		SVID_REQUESTED_WAFER_CARRIER_LOAD_PORT_NUMBER											3204
#define		SVID_REQUESTED_WAFER_CARRIER_LOAD_CARRIER_ID											3205
#define		SVID_REQUESTED_WAFER_CARRIER_LOAD_CARRIER_TYPE											3206
#define		SVID_REQUESTED_WAFER_CARRIER_LOAD_CARRIER_SLOT_MAP										3207
#define		SVID_WAFER_CARRIER_LOADED_PORT_NUMBER													3208
#define		SVID_WAFER_CARRIER_LOADED_CARRIER_ID													3209
#define		SVID_WAFER_CARRIER_LOADED_CARRIER_TYPE													3210
#define		SVID_WAFER_CARRIER_LOADED_CARRIER_SLOT_MAP												3211
#define		SVID_WAFER_CARRIER_LOADED_FAILURE_PORT_NUMBER											3212
#define		SVID_WAFER_CARRIER_LOADED_FAILURE_CARRIER_ID											3213
#define		SVID_WAFER_CARRIER_LOADED_FAILURE_CARRIER_TYPE											3214
#define		SVID_WAFER_CARRIER_LOADED_FAILURE_CARRIER_SLOT_MAP										3215
#define		SVID_WAFER_CARRIER_LOADED_FAILURE_PORT_ERROR_DESCRIPTION								3216
#define		SVID_REQUESTED_WAFER_CARRIER_ABORT_PORT_NUMBER											3217
#define		SVID_REQUESTED_WAFER_CARRIER_ABORT_CARRIER_ID											3218
#define		SVID_REQUESTED_WAFER_CARRIER_ABORT_CARRIER_TYPE											3219
#define		SVID_REQUESTED_WAFER_CARRIER_ABORT_CARRIER_SLOT_MAP										3220
#define		SVID_WAFER_CARRIER_ABORTED_PORT_NUMBER													3221
#define		SVID_WAFER_CARRIER_ABORTED_CARRIER_ID													3222
#define		SVID_WAFER_CARRIER_ABORTED_CARRIER_TYPE													3223
#define		SVID_WAFER_CARRIER_ABORTED_CARRIER_SLOT_MAP												3224
#define		SVID_WAFER_CARRIER_ABORTED_FAILURE_PORT_NUMBER											3225
#define		SVID_WAFER_CARRIER_ABORTED_FAILURE_CARRIER_ID											3226
#define		SVID_WAFER_CARRIER_ABORTED_FAILURE_CARRIER_TYPE											3227
#define		SVID_WAFER_CARRIER_ABORTED_FAILURE_CARRIER_SLOT_MAP										3228
#define		SVID_WAFER_CARRIER_ABORTED_FAILURE_PORT_ERROR_DESCRIPTION								3229
#define		SVID_REQUESTED_WAFER_CARRIER_UNLOAD_PORT_NUMBER											3230
#define		SVID_REQUESTED_WAFER_CARRIER_UNLOAD_CARRIER_ID											3231
#define		SVID_REQUESTED_WAFER_CARRIER_UNLOAD_CARRIER_TYPE										3232
#define		SVID_REQUESTED_WAFER_CARRIER_UNLOAD_CARRIER_SLOT_MAP									3233
#define		SVID_WAFER_CARRIER_UNLOADED_PORT_NUMBER													3234
#define		SVID_WAFER_CARRIER_UNLOADED_CARRIER_ID													3235
#define		SVID_WAFER_CARRIER_UNLOADED_CARRIER_TYPE												3236
#define		SVID_WAFER_CARRIER_UNLOADED_CARRIER_SLOT_MAP											3237
#define		SVID_WAFER_CARRIER_UNLOADED_FAILURE_PORT_NUMBER											3238
#define		SVID_WAFER_CARRIER_UNLOADED_FAILURE_CARRIER_ID											3239
#define		SVID_WAFER_CARRIER_UNLOADED_FAILURE_CARRIER_TYPE										3240
#define		SVID_WAFER_CARRIER_UNLOADED_FAILURE_CARRIER_SLOT_MAP									3241
#define		SVID_WAFER_CARRIER_UNLOADED_FAILURE_PORT_ERROR_DESCRIPTION								3242
#define		SVID_UNEXPECTED_WAFER_CARRIER_DETECTED_PORT_NUMBER										3243
#define		SVID_UNEXPECTED_WAFER_CARRIER_REMOVAL_PORT_NUMBER										3244
#define		SVID_WAFER_CARRIER_ID_UNREADABLE_PORT_NUMBER											3245
#define		SVID_WAFER_CARRIER_ID_MANUALLY_INPUTTED_PORT_NUMBER										3246
#define		SVID_WAFER_CARRIER_ID_MANUALLY_INPUTTED_CARRIER_ID										3247
#define		SVID_READY_TO_LOAD_THE_NEXT_WAFER_CARRIER_PORT_NUMBER									3248
#define		SVID_READY_TO_UNLOAD_THE_FINISHED_WAFER_CARRIER_PORT_NUMBER								3249
#define		SVID_READY_TO_UNLOAD_THE_FINISHED_WAFER_CARRIER_ID										3250
#define		SVID_WAFER_CARRIER_TYPE_DID_NOT_MATCH_EQUIPMENT_PORT_NUMBER								3251

#define		SVID_REQUESTED_WAFER_CARRIER_LOAD_CARRIER_WAFER_COUNT									3252
#define		SVID_WAFER_CARRIER_LOADED_WAFER_COUNT													3253
#define		SVID_WAFER_CARRIER_LOADED_FAILURE_WAFER_COUNT											3254


#define		SVID_WAFER_CARRIER_IDS_AT_LOAD_PORT1													3260
#define		SVID_WAFER_CARRIER_IDS_AT_LOAD_PORT2													3261
#define		SVID_WAFER_CARRIER_IDS_AT_LOAD_PORT3													3262
#define		SVID_WAFER_CARRIER_IDS_AT_LOAD_PORT4													3263
#define		SVID_WAFER_CARRIER_TYPES_AT_LOAD_PORT1													3270
#define		SVID_WAFER_CARRIER_TYPES_AT_LOAD_PORT2													3271
#define		SVID_WAFER_CARRIER_TYPES_AT_LOAD_PORT3													3272
#define		SVID_WAFER_CARRIER_TYPES_AT_LOAD_PORT4													3273
#define		SVID_WAFER_CARRIER_QUANTITY_AT_LOAD_PORT1												3280
#define		SVID_WAFER_CARRIER_QUANTITY_AT_LOAD_PORT2												3281
#define		SVID_WAFER_CARRIER_QUANTITY_AT_LOAD_PORT3												3282
#define		SVID_WAFER_CARRIER_QUANTITY_AT_LOAD_PORT4												3283
#define		SVID_WAFER_CARRIER_SLOT_MAP_AT_LOAD_PORT1												3290
#define		SVID_WAFER_CARRIER_SLOT_MAP_AT_LOAD_PORT2												3291
#define		SVID_WAFER_CARRIER_SLOT_MAP_AT_LOAD_PORT3												3292
#define		SVID_WAFER_CARRIER_SLOT_MAP_AT_LOAD_PORT4												3293
#define		SVID_REQUESTED_WAFER_CARRIER_START_PROCESS_PORT_NUMBER									3294
#define		SVID_REQUESTED_WAFER_CARRIER_START_PROCESS_CARRIER_ID									3295
#define		SVID_REQUESTED_WAFER_CARRIER_START_PROCESS_CARRIER_TYPE									3296
#define		SVID_REQUESTED_WAFER_CARRIER_START_PROCESS_CARRIER_SLOT_MAP								3297
#define		SVID_REJECTED_WAFER_CARRIER_PORT_NUMBER													3298
#define		SVID_REJECTED_WAFER_CARRIER_CARRIER_ID													3299
#define		SVID_REJECTED_WAFER_CARRIER_CARRIER_TYPE												3300
#define		SVID_WAFER_CARRIER_STARTED_PROCESS_PORT_NUMBER											3301
#define		SVID_WAFER_CARRIER_STARTED_PROCESS_CARRIER_ID											3302
#define		SVID_WAFER_CARRIER_STARTED_PROCESS_CARRIER_TYPE											3303
#define		SVID_WAFER_CARRIER_STARTED_PROCESS_CARRIER_SLOT_MAP										3304
#define		SVID_WAFER_CARRIER_FINISHED_PROCESS_PORT_NUMBER											3305
#define		SVID_WAFER_CARRIER_FINISHED_PROCESS_CARRIER_ID											3306
#define		SVID_WAFER_CARRIER_FINISHED_PROCESS_CARRIER_TYPE										3307
#define		SVID_WAFER_CARRIER_FINISHED_PROCESS_CARRIER_SLOT_MAP									3308



#define		SVID_RECIPE_LOAD_SUCCESSFULLY_ASSIGNED_WAFER_ID											3309
#define		SVID_RECIPE_LOAD_SUCCESSFULLY_ASSIGNED_RECIPE_ID										3310
#define		SVID_RECIPE_LOAD_FAILED_WAFER_ID														3311
#define		SVID_RECIPE_LOAD_FAILED_RECIPE_ID														3312


#define		SVID_APC_PARAMETERS_LOAD_SUCCESSFULLY_ASSIGNED_APC_PARAMETER_WAFER_ID					3313
#define		SVID_APC_PARAMETERS_LOAD_SUCCESSFULLY_ASSIGNED_APC_PARAMETER_WAFER_ID_NAME_LIST			3314
#define		SVID_APC_PARAMETERS_LOAD_SUCCESSFULLY_ASSIGNED_APC_PARAMETER_WAFER_ID_VALUE_LIST		3315

#define		SVID_APC_PARAMETERS_LOAD_FAILED_APC_PARAMETER_WAFER_ID									3316
#define		SVID_APC_PARAMETERS_LOAD_FAILED_APC_PARAMETER_NAME_LIST									3317
#define		SVID_APC_PARAMETERS_LOAD_FAILED_APC_PARAMETER_VALUE_LIST								3318


#define		SVID_REQUESTED_WAFER_CARRIER_START_PROCESS_WAFER_COUNT									3319
#define		SVID_WAFER_CARRIER_STARTED_PROCESS_WAFER_COUNT											3320

#define		SVID_INPUT_WAFER_SELECT_CARRIERID														3330
#define		SVID_INPUT_WAFER_SELECT_WAFERLIST														3331
#define		SVID_INPUT_SLOT_SELECT_CARRIERID														3332
#define		SVID_INPUT_SLOT_SELECT_SLOTLIST															3333
#define		SVID_OUTPUT_SLOT_SELECT_CARRIERID														3334
#define		SVID_OUTPUT_SLOT_SELECT_SLOTLIST														3335


#define		SVID_WAFER_RING_LOADED_TO_ID_READ_ZONE_WAFER_ID											3800
#define		SVID_WAFER_RING_UNLOADED_FROM_ID_READ_ZONE_WAFER_ID										3801
#define		SVID_WAFER_RING_ERROR_AT_ID_READ_ZONE_WAFER_ID											3802
#define		SVID_WAFER_RING_ID_MANUALLY_TYPED_WAFER_ID												3803
#define		SVID_REQUEST_TO_PROCESS_WAFER_WAFER_ID													3804
#define		SVID_WAFER_RING_LOADED_TO_STRETCHING_MODULE_WAFER_ID									3805
#define		SVID_WAFER_TAPE_STRETCHED_WAFER_ID														3806
#define		SVID_OUTER_RING_PUT_AROUND_STRETCHED_WAFER_TAPE_WAFER_ID								3807
#define		SVID_WAFER_RING_UNLOADED_FROM_STRETCHING_MODULE_WAFER_ID								3808
#define		SVID_BARCODE_LABEL_PRINTED_WAFER_ID														3809
#define		SVID_BARCODE_LABEL_ATTACHED_TO_WAFER_TAPE_WAFER_ID										3810
#define		SVID_BARCODE_LABEL_MATCHED_WAFER_ID_WAFER_ID											3811
#define		SVID_BARCODE_LABEL_DID_NOT_MATCH_WAFER_ID_ORIGINAL_WAFER_ID								3812
#define		SVID_BARCODE_LABEL_DID_NOT_MATCH_WAFER_ID_STICKER_WAFER_ID								3813
#define		SVID_WAFER_RING_UNLOADED_FROM_CASSETTE_LOAD_PORT_NUMBER									3814
#define		SVID_WAFER_RING_UNLOADED_FROM_CASSETTE_WAFER_CARRIER_ID									3815
#define		SVID_WAFER_RING_UNLOADED_FROM_CASSETTE_SLOT_NUMBER										3816
#define		SVID_WAFER_RING_UNLOAD_ERROR_FROM_CASSETTE_LOAD_PORT_NUMBER								3817
#define		SVID_WAFER_RING_UNLOAD_ERROR_FROM_CASSETTE_WAFER_CARRIER_ID								3818
#define		SVID_WAFER_RING_UNLOAD_ERROR_FROM_CASSETTE_SLOT_NUMBER									3819
#define		SVID_WAFER_RING_UNLOAD_ERROR_FROM_CASSETTE_ERROR_DESCRIPTION							3820
#define		SVID_WAFER_RING_LOADED_TO_CASSETTE_LOAD_PORT_NUMBER										3821
#define		SVID_WAFER_RING_LOADED_TO_CASSETTE_WAFER_CARRIER_ID										3822
#define		SVID_WAFER_RING_LOADED_TO_CASSETTE_SLOT_NUMBER											3823
#define		SVID_WAFER_RING_LOADED_TO_CASSETTE_WAFER_ID												3824
#define		SVID_WAFER_RING_LOAD_ERROR_TO_CASSETTE_LOAD_PORT_NUMBER									3825
#define		SVID_WAFER_RING_LOAD_ERROR_TO_CASSETTE_WAFER_CARRIER_ID									3826
#define		SVID_WAFER_RING_LOAD_ERROR_TO_CASSETTE_SLOT_NUMBER										3827
#define		SVID_WAFER_RING_LOAD_ERROR_TO_CASSETTE_WAFER_ID											3828
#define		SVID_WAFER_RING_LOAD_ERROR_TO_CASSETTE_ERROR_DESCRIPTION								3829
#define		SVID_WAFER_SLOT_NUMBER_OF_THE_WAFER_MOST_RECENTLY_STARTED_PROCESSING					3830
#define		SVID_WAFER_ID_OF_THE_WAFER_MOST_RECENTLY_STARTED_PROCESSING								3831
#define		SVID_WAFER_SLOT_NUMBER_OF_THE_WAFER_MOST_RECENTLY_FINISHED_PROCESSING					3832
#define		SVID_WAFER_ID_OF_THE_WAFER_MOST_RECENTLY_FINISHED_PROCESSING							3833
#define		SVID_WAFER_SLOT_NUMBER_OF_THE_WAFER_MOST_RECENTLY_ABORTED								3834
#define		SVID_WAFER_ID_OF_THE_WAFER_MOST_RECENTLY_ABORTED										3835
#define		SVID_WAFER_SLOT_NUMBER_OF_THE_WAFER_MOST_RECENTLY_MANUAL_REMOVED						3836
#define		SVID_WAFER_ID_OF_THE_WAFER_MOST_RECENTLY_MANUAL_REMOVED									3837

#define		SVID_REQUEST_WAFER_SPLIT_CARRIER_ID														3838
#define		SVID_REQUEST_WAFER_SPLIT_WAFER_ID														3839
#define		SVID_REQUEST_WAFER_SPLIT_SLOT_NO														3840

#define     SVID_WAFER_ID_WAFER_SPLIT_COMPLETED														3841
#define     SVID_CARRIER_ID_WAFER_SPLIT_COMPLETED													3842
#define     SVID_SLOT_NO_WAFER_SPLIT_COMPLETED														3843

#define     SVID_OUTOUT_CASSETTE_SLOT_CHECK_ERROR_SLOTNO											3844
#define		SVID_OUTOUT_CASSETTE_SLOT_CHECK_ERROR_PORTNO											3845
#define		SVID_EVENTRECIPEID														3900




//============== RECIPE CCODE ====================================
#define		CCODE_WAFER_SIZE_SELECT							"WAFER_SIZE_SELECT"
#define		CCODE_SCANNER_SELECT							"SCANNER_SELECT"
#define		CCODE_FACE_SELECT								"FACE_SELECT"
#define		CCODE_NC_SELECT									"NC_SELECT"
#define		CCODE_TAPE_EXPAND_LENGTH						"TAPE_EXPAND_LENGTH"
#define		CCODE_TAPE_EXPAND_SPEED							"TAPE_EXPAND_SPEED"
#define		CCODE_EXPAND_CHUCK_TEMP							"EXPAND_CHUCK_TEMP"
#define		CCODE_EXPAND_CHUCK_TEMP_OFFSET_DATA				"EXPAND_CHUCK_TEMP_OFFSET_DATA"
#define		CCODE_EXPAND_HEATING_TIME						"EXPAND_HEATING_TIME"
#define		CCODE_EXPAND_END_WAIT_TIME						"EXPAND_END_WAIT_TIME"
#define		CCODE_OUT_RING_LOCK_SPEED						"OUT_RING_LOCK_SPEED"


