//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// CUON.rc에서 사용되고 있습니다.
//
#define IDCANCEL                        2
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_CUON_FORM                   101
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_CUONTYPE                    130
#define IDD_TITLE_CUON                  313
#define IDD_DIALOG_NUMBER_PAD           320
#define IDD_DIALOG_MAIN                 321
#define IDD_DIALOG_GEM                  324
#define IDD_DIALOG_GEM_PARAMETER        325
#define IDD_DIALOG_NUMBER_PAD2          325
#define IDD_DIALOG_BOX                  327
#define IDD_DIALOG_SELECT               328
#define IDD_DIALOG_LOADPORT             329
#define IDD_DIALOG_LOADPORT_SETTING     330
#define IDD_DIALOG_SYSTEM_SETTING       332
#define IDD_DIALOG_SYSTEM_RCP           333
#define IDD_DIALOG_SYSTEM_MOTOR         334
#define IDD_DIALOG_SYSTEM_INTERFACE     335
#define IDD_DIALOG_ERROR_DISPLAY        337
#define IDD_DIALOG_BOX_WARNING          338
#define IDD_DIALOG_LOGIN                339
#define IDD_DIALOG_SYSTEM_USER          340
#define IDD_DIALOG_LOG                  341
#define IDI_ICON1                       348
#define IDC_LOAD_STOP                   1000
#define IDC_MAIN_START                  1000
#define IDC_LOAD_STOP2                  1001
#define IDC_MAIN_HOME                   1001
#define IDC_LOAD_STOP3                  1002
#define IDC_MAIN_RESET                  1002
#define IDC_LOAD_STOP4                  1003
#define IDC_MAIN_STOP                   1003
#define IDC_EDIT1                       1004
#define IDC_WORK_END                    1004
#define IDC_LOAD_STOP5                  1004
#define IDC_LAST_WORK                   1004
#define IDC_BUTTON2                     1005
#define IDC_TAB1                        1005
#define IDC_OPENER_SET                  1005
#define IDC_LOAD_STOP6                  1005
#define IDC_EDIT2                       1005
#define IDC_WORKEND                     1005
#define IDC_BTNENHCTRL1                 1006
#define IDC_F1                          1006
#define IDC_RFID_SET                    1006
#define IDC_LOAD_STOP7                  1006
#define IDC_TOP_LOGO                    1007
#define IDC_RESET                       1007
#define IDC_LOAD_STOP8                  1007
#define IDC_TOP_MSG                     1008
#define IDC_START                       1008
#define IDC_LOAD_STOP9                  1008
#define IDC_TOP_LOGIN                   1009
#define IDC_BUTTON1                     1009
#define IDC_MAIN_BUT2                   1009
#define IDC_OPENER_OPEN                 1009
#define IDC_LOAD_STOP10                 1009
#define IDC_TOP_MSG2                    1009
#define IDC_TOP_LIGHT                   1010
#define IDC_MAIN_BUT3                   1010
#define IDC_RFID_OPEN                   1010
#define IDC_LOAD_STOP11                 1010
#define IDC_TOP_LOGO2                   1010
#define IDC_TOP_RESET                   1011
#define IDC_MAIN_EXIT                   1011
#define IDC_MAIN_START2                 1011
#define IDC_TOP_LOGO3                   1011
#define IDC_TOP_BUZZER                  1012
#define IDC_HOME                        1012
#define IDC_MAIN_STOP2                  1012
#define IDC_TOP_MSG3                    1012
#define IDC_TOP_DATE                    1013
#define IDC_STOP                        1013
#define IDC_LAST_WORK2                  1013
#define IDC_TOP_MSG4                    1013
#define IDC_TOP_PLC_STAT                1014
#define IDC_TITLE_PLC_STAT              1014
#define IDC_WORKEND2                    1014
#define IDC_TOP_MSG5                    1014
#define IDC_TOP_PLC                     1015
#define IDC_TITLE_PLC_STAT2             1015
#define IDC_TOP_GEM_STAT                1016
#define IDC_MAIN_BUT1                   1016
#define IDC_F2                          1016
#define IDC_TOP_GEM                     1017
#define IDC_BUTTON3                     1017
#define IDC_CHECK                       1017
#define IDC_TITLE_PLC_STAT3             1017
#define IDC_TOP_MSG7                    1017
#define IDC_TOP_MOT1                    1018
#define IDC_COMMAND1                    1018
#define IDC_TITLE_PLC_STAT4             1018
#define IDC_TOP_DATE2                   1018
#define IDC_TOP_SN                      1018
#define IDC_TOP_MSG8                    1018
#define IDC_LOGIN_ID                    1018
#define IDC_TOP_MOT2                    1019
#define IDC_BUTTON4                     1019
#define IDC_TITLE_PLC_STAT5             1019
#define IDC_ENG_MAIN_TAPE2              1019
#define IDC_TOP_DATE3                   1019
#define IDC_LOGIN_LEVEL                 1019
#define IDC_TOP_1                       1020
#define IDC_TITLE_PLC_STAT6             1020
#define IDC_TOP_DATE4                   1020
#define IDC_TOP_RCP                     1021
#define IDC_F3                          1021
#define IDC_BUT_AUTO                    1021
#define IDC_TOP_2                       1022
#define IDC_F4                          1022
#define IDC_TOP_RCP2                    1022
#define IDC_BUT_SYSTEM                  1022
#define IDC_TOP_LOTID                   1023
#define IDC_TOP_3                       1024
#define IDC_TOP_GEM2                    1024
#define IDC_BUT_GEM                     1024
#define IDC_TOP_OPR                     1025
#define IDC_TOP_GEM3                    1025
#define IDC_BUT_LOG                     1025
#define IDC_TOP_GEM_STAT2               1026
#define IDC_BUT_CST                     1026
#define IDC_TOP_GEM4                    1027
#define IDC_BUT_IO_CHECK                1027
#define IDC_BUT_RECIPE                  1027
#define IDC_CONFIRM_BOX_TEXT            1028
#define IDC_TOP_GEM5                    1028
#define IDC_BUT_MOTOR_CHECK             1028
#define IDC_TOP_LEVEL                   1028
#define IDC_SELECT_MSG                  1029
#define IDC_TOP_GEM6                    1029
#define IDC_BUT_CAMERA                  1029
#define IDC_TOP_ID                      1029
#define IDC_TOP_LEVEL2                  1029
#define IDC_SELECT_LIST                 1030
#define IDC_TOP_GEM7                    1030
#define IDC_TOP_OPERATOR                1030
#define IDC_TOP_LEVEL3                  1030
#define IDC_BUT_COMM                    1030
#define IDC_SELECT_ENTER                1031
#define IDC_TOP_LIGHT2                  1031
#define IDC_TOP_MONI1                   1031
#define IDC_TOP_LEVEL4                  1031
#define IDC_SELECT_CLOSE                1032
#define IDC_TOP_LIGHT3                  1032
#define IDC_TOP_MONI2                   1032
#define IDC_CONFIRM_ENTER               1033
#define IDC_TOP_DATE5                   1033
#define IDC_CONFIRM_CLOSE               1034
#define IDC_TOP_DATE6                   1034
#define IDC_TOP_MODEL                   1034
#define IDC_TOP_DATE7                   1035
#define IDC_TOP_SOFT                    1035
#define IDC_COMBO_COM                   1036
#define IDC_TOP_CUSTOMER                1036
#define IDC_COMBO_PORT                  1037
#define IDC_TOP_KEYBOARD                1037
#define IDC_MSCOMM1                     1038
#define IDC_MSCOMM2                     1039
#define IDC_MSCOMM3                     1040
#define IDC_MSCOMM4                     1041
#define IDC_MSCOMM5                     1042
#define IDC_MSCOMM6                     1043
#define IDC_OPENER_LED                  1044
#define IDC_MSCOMM7                     1045
#define IDC_COMBO_COM2                  1046
#define IDC_COMBO_PORT2                 1047
#define IDC_RFID_LED                    1048
#define IDC_MSCOMM8                     1049
#define IDC_MSCOMM9                     1050
#define IDC_MSCOMM10                    1051
#define IDC_MSCOMM11                    1052
#define IDC_MSCOMM12                    1053
#define IDC_MSCOMM13                    1054
#define IDC_BUTTON_START                1055
#define IDC_MSCOMM14                    1055
#define IDC_MSCOMM15                    1056
#define IDC_MAIN_HOME1                  1057
#define IDC_MSCOMM16                    1057
#define IDC_MAIN_HOME2                  1058
#define IDC_MSCOMM17                    1058
#define IDC_MAIN_HOME3                  1059
#define IDC_MSCOMM18                    1059
#define IDC_MAIN_HOME4                  1060
#define IDC_COMBO_COM3                  1060
#define IDC_MAIN_HOME5                  1061
#define IDC_COMBO_COM4                  1061
#define IDC_MAIN_HOME6                  1062
#define IDC_BUTTON5                     1062
#define IDC_MAIN_HOME7                  1063
#define IDC_MAIN_HOME8                  1064
#define IDC_MAIN_HOME9                  1065
#define IDC_MAIN_HOME10                 1066
#define IDC_MAIN_HOME11                 1067
#define IDC_MAIN_HOME12                 1068
#define IDC_MAIN_HOME13                 1069
#define IDC_RCP_GRID                    1069
#define IDC_MAIN_HOME14                 1070
#define IDC_RCP_GRID2                   1070
#define IDC_MOTOR_LIMIT_CCW             1071
#define IDC_MAIN_HOME15                 1071
#define IDC_MOTOR_LIMIT_CW              1072
#define IDC_MAIN_HOME16                 1072
#define IDC_SYSTEM_RCP                  1072
#define IDC_MOTOR_HOME                  1073
#define IDC_MAIN_HOME17                 1073
#define IDC_SYSTEM_MOTOR                1073
#define IDC_MOTOR_BUT_CCW               1074
#define IDC_MAIN_HOME18                 1074
#define IDC_SYSTEM_INTERFACE            1074
#define IDC_MOTOR_BUT_CW                1075
#define IDC_MAIN_HOME19                 1075
#define IDC_SYSTEM_COMM                 1075
#define IDC_MOTOR_BUT_HOME              1076
#define IDC_TENKEY_1                    1076
#define IDC_MAIN_HOME20                 1076
#define IDC_SYSTEM_TAPE                 1076
#define IDC_MOTOR_BUT_JOG_SPEED_HI      1077
#define IDC_TENKEY_2                    1077
#define IDC_MAIN_HOME21                 1077
#define IDC_RCP_NEW                     1077
#define IDC_SYSTEM_USER                 1077
#define IDC_MOTOR_BUT_JOG_SPEED_MID     1078
#define IDC_TENKEY_3                    1078
#define IDC_MAIN_HOME22                 1078
#define IDC_RCP_CREATE                  1078
#define IDC_SYSTEM_SELECT               1078
#define IDC_MOTOR_BUT_JOG_SPEED_LOW     1079
#define IDC_TENKEY_4                    1079
#define IDC_MAIN_HOME23                 1079
#define IDC_RCP_CANCEL                  1079
#define IDC_SYSTEM_CONFIG               1079
#define IDC_TENKEY_5                    1080
#define IDC_MAIN_HOME24                 1080
#define IDC_RCP_DELETE                  1080
#define IDC_SYSTEM_MANUAL               1080
#define IDC_TENKEY_6                    1081
#define IDC_MAIN_HOME25                 1081
#define IDC_RCP_CHANGE                  1081
#define IDC_SYSTEM_IO                   1081
#define IDC_TENKEY_7                    1082
#define IDC_MAIN_HOME26                 1082
#define IDC_RCP_SAVE                    1082
#define IDC_SYSTEM_MOTOCHECK            1082
#define IDC_TENKEY_8                    1083
#define IDC_MAIN_HOME27                 1083
#define IDC_EDIT3                       1083
#define IDC_TENKEY_9                    1084
#define IDC_MAIN_HOME28                 1084
#define IDC_INTERFACE_GRID              1084
#define IDC_TENKEY_0                    1085
#define IDC_MAIN_HOME29                 1085
#define IDC_INTERFACE_GRID2             1085
#define IDC_EDIT4                       1085
#define IDC_TENKEY_DOT                  1086
#define IDC_MAIN_HOME30                 1086
#define IDC_RCP_NAME                    1086
#define IDC_TENKEY_CLOSE                1087
#define IDC_MAIN_HOME31                 1087
#define IDC_MOTOR_GRID                  1087
#define IDC_TENKEY_COPY                 1088
#define IDC_MAIN_HOME32                 1088
#define IDC_MOTOR_GRID2                 1088
#define IDC_TENKEY_CLEAR                1089
#define IDC_MAIN_HOME33                 1089
#define IDC_MOTOR_INCH                  1089
#define IDC_TENKEY_DASH                 1090
#define IDC_MAIN_HOME34                 1090
#define IDC_MOTOR_SAVE                  1090
#define IDC_TENKEY_ENTER                1091
#define IDC_MAIN_HOME35                 1091
#define IDC_COMBO1                      1091
#define IDC_NUMBER_MSG2                 1092
#define IDC_MAIN_HOME36                 1092
#define IDC_COMBO2                      1092
#define IDC_INTERFACE_COMBO             1092
#define IDC_NUMBER_MSG                  1093
#define IDC_MAIN_HOME37                 1093
#define IDC_INTERFACE_SAVE              1093
#define IDC_NUMBER_MSG3                 1094
#define IDC_MAIN_HOME38                 1094
#define IDC_ERROR_CLOSE                 1094
#define IDC_NUMBER_CUR                  1095
#define IDC_MAIN_HOME39                 1095
#define IDC_MOTOR_CUR_POS               1096
#define IDC_NUMBER_BACK2                1096
#define IDC_MAIN_HOME40                 1096
#define IDC_LIST                        1096
#define IDC_LOGIN_PASS                  1097
#define IDC_LOGIN_ENTER                 1098
#define IDC_WARNING_OK                  1099
#define IDC_LOGIN_ENTER2                1099
#define IDC_WARNING_CLOSE               1100
#define IDC_ERROR_RESET                 1101
#define IDC_USER_SAVE                   1102
#define IDC_ERROR_BUZZER                1102
#define IDC_USER_GRID                   1103
#define IDC_ERROR_RETRY                 1103
#define IDC_USER_NEW                    1105
#define IDC_USER_CREATE                 1106
#define IDC_USER_CANCEL                 1107
#define IDC_EDIT_MIN                    1108
#define IDC_USER_DELETE                 1108
#define IDC_EDIT_MAX                    1109
#define IDC_RCP_EDIT                    1109
#define IDC_USER_LIST                   1110
#define IDC_LOGIN_CANCEL                1111
#define IDC_CONTROL1                    1114
#define IDC_EZGEMCTRL                   1116
#define IDC_CHECK1                      1116
#define IDC_BUTTON_STOP                 1117
#define IDC_RADIO1                      1117
#define IDC_BUTTON_REMOTE               1118
#define IDC_BUTTON_LOCAL                1119
#define IDC_BUTTON_OFFLINE              1120
#define IDC_BUTTON_PARAMETER            1121
#define IDC_STATIC_CONTROL              1122
#define IDC_EDIT_IP                     1123
#define IDC_STATIC_EQUIPMENTSTATE       1123
#define IDC_EDIT_PORT                   1124
#define IDC_EDIT_DEVID                  1124
#define IDC_EDIT_DEVICEID               1125
#define IDC_EDIT_PORTID                 1125
#define IDC_EDIT_T3                     1126
#define IDC_STATIC_CONNECT              1126
#define IDC_EDIT_T5                     1127
#define IDC_EDIT_LINKTEST               1128
#define IDC_EDIT_T6                     1129
#define IDC_EDIT_T7                     1130
#define IDC_EDIT_T8                     1131
#define IDC_EDIT_RETRYLIMIT             1132
#define IDC_LIST1                       1134

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        350
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1118
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
